[package]
name = 'go'
version = '2.5.1'
description = ''
license = ''

[[source]]
source = ''

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir -pv $OUT/usr/local

wget https://go.dev/dl/go1.21.4.linux-amd64.tar.gz -O /tmp/go1.21.4.linux-amd64.tar.gz
tar -C $OUT/usr/local -xzf /tmp/go1.21.4.linux-amd64.tar.gz
'''
