[package]
name = 'netavark'
version = '1.10.3'
description = ''
license = ''

[[source]]
source = 'https://github.com/containers/netavark/archive/refs/tags/v1.10.3.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

make
make DESTDIR=$OUT install
'''
