[package]
name = 'netavark'
version = '1.10.3'
description = ''
license = ''

[[source]]
source = 'https://github.com/containers/netavark/archive/refs/tags/v1.10.3.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

export PATH=$PATH:$HOME/.cargo/bin

make

# remove trailing / from $OUT
# OUT=${OUT%/}

# make DESTDIR=$OUT PREFIX=/usr install

find .

mkdir -pv $OUT/usr/libexec/podman
cp bin/netavark $OUT/usr/libexec/podman/netavark
cp bin/netavark-dhcp-proxy-client $OUT/usr/libexec/podman/netavark-dhcp-proxy-client

mkdir -pv $OUT/etc/systemd/system/
cp ./contrib/systemd/system/netavark-dhcp-proxy.socket $OUT/etc/systemd/system/netavark-dhcp-proxy.socket
cp ./contrib/systemd/system/netavark-dhcp-proxy.service.in $OUT/etc/systemd/system/netavark-dhcp-proxy.service
cp ./contrib/systemd/system/netavark-firewalld-reload.service.in $OUT/etc/systemd/system/netavark-firewalld-reload.service
'''
