[package]
name = 'pango'
version = '1.51.2'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/pango/1.51/pango-1.51.2.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr          \
            --buildtype=release    \
            --wrap-mode=nofallback \
            ..

ninja
DESTDIR=$OUT ninja install
'''
