[package]
name = 'btrfs-progs'
version = '6.7.1'
description = ''
license = ''

[[source]]
source = 'https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.7.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr           \
            --disable-static        \
            --disable-documentation

make -j$(nproc)
make DESTDIR=$OUT install
'''
