[package]
name = 'nss'
version = '2.5.1'
description = ''
license = ''

[[source]]
source = 'https://download.savannah.gnu.org/releases/attr/attr-2.5.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

#wget https://www.linuxfromscratch.org/patches/blfs/12.1/nss-3.98-standalone-1.patch
#patch -Np1 -i ./nss-3.98-standalone-1.patch

cd nss

make BUILD_OPT=1                      \
  NSPR_INCLUDE_DIR=/usr/include/nspr  \
  USE_SYSTEM_ZLIB=1                   \
  ZLIB_LIBS=-lz                       \
  NSS_ENABLE_WERROR=0                 \
  $([ $(uname -m) = x86_64 ] && echo USE_64=1) \
  $([ -f /usr/include/sqlite3.h ] && echo NSS_USE_SYSTEM_SQLITE=1)

cd ../dist

install -v -m755 Linux*/lib/*.so              $OUT/usr/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $OUT/usr/lib

install -v -m755 -d                           $OUT/usr/include/nss
cp -v -RL {public,private}/nss/*              $OUT/usr/include/nss

install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} $OUT/usr/bin

install -v -m644 Linux*/lib/pkgconfig/nss.pc  $OUT/usr/lib/pkgconfig
'''
