[package]
name = 'gjs'
version = '1.78.4'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gjs/1.78/gjs-1.78.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir gjs-build
cd gjs-build

meson setup --prefix=/usr          \
            --buildtype=release    \
            --wrap-mode=nofallback \
            ..

ninja
DESTDIR=$OUT ninja install
'''
