[package]
name = 'fribidi'
version = '1.0.13'
description = ''
license = ''

[[source]]
source = 'https://github.com/fribidi/fribidi/releases/download/v1.0.13/fribidi-1.0.13.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja

DESTDIR=$OUT ninja install
'''
