[package]
name = 'sdl2'
version = '2.30.0'
description = ''
license = ''

[[source]]
source = 'https://www.libsdl.org/release/SDL2-2.30.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install

rm -v $OUT/usr/lib/libSDL2*.a
'''
