[package]
name = 'selinux'
version = '3.5'
description = 'SELinux Userspace'
license = ''

[[source]]
source = 'https://github.com/SELinuxProject/selinux.git'
git_ref = '3.5'

[build]
script = '''
set -eux # o pipefail

apt-get install --no-install-recommends --no-install-suggests \
    bison \
    flex \
    gawk \
    gcc \
    gettext \
    make \
    libaudit-dev \
    libbz2-dev \
    libcap-dev \
    libcap-ng-dev \
    libcunit1-dev \
    libglib2.0-dev \
    libpcre2-dev \
    pkgconf \
    python3 \
    systemd \
    xmlto

make DESTDIR=$OUT install
'''
