[package]
name = 'libwacom'
version = '2.10.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/linuxwacom/libwacom/releases/download/libwacom-2.10.0/libwacom-2.10.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Dtests=disabled

ninja
DESTDIR=$OUT ninja install
'''
