[package]
name = 'graphene'
version = '1.10.8'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/graphene/1.10/graphene-1.10.8.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
