[package]
name = 'gmp'
version = '6.3.0'
description = 'gmp'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr            \
            --enable-cxx             \
            --disable-static         \
            --build=x86_64-linux-gnu \
            --docdir=/usr/share/doc/gmp-6.3.0

make -j$(nproc)
make DESTDIR=$OUT install
'''
