[package]
name = 'gmp'
version = '6.3.0'
description = 'gmp'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd gmp-6.3.0

./configure --prefix=/usr    \
            --enable-cxx     \
            --disable-static \
            --docdir=/usr/share/doc/gmp-6.3.0

make
make DESTDIR=$OUT install
'''
