[package]
name = 'linux-api-headers'
version = '6.4.12'
description = ''
license = ''

[[source]]
source = 'https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.4.12.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

make mrproper

make headers
find usr/include -type f ! -name '*.h' -delete

mkdir -p $OUT/usr/include

cp -rv usr/include $OUT/usr/include
'''
