[package]
name = 'rest'
version = '0.9.1'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/rest/0.9/rest-0.9.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr       \
            --buildtype=release \
            -Dexamples=false    \
            -Dgtk_doc=false     \
            ..

ninja
DESTDIR=$OUT ninja install
'''
