[package]
name = 'flatpak'
version = '1.14.5'
description = ''
license = ''

[[source]]
source = 'https://github.com/flatpak/flatpak/releases/download/1.14.5/flatpak-1.14.5.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

./configure             \
    --prefix=/usr       \
    --sysconfdir=/etc   \
    --with-systemd      \

make
make DESTDIR=$OUT install
'''
