[package]
name = 'flatpak'
version = '1.14.5'
description = ''
license = ''

[[source]]
source = 'https://github.com/flatpak/flatpak.git'
git_ref = '1.14.5'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
