[package]
name = 'dbus'
version = '1.14.8'
description = ''
license = ''

[[source]]
source = 'https://dbus.freedesktop.org/releases/dbus/dbus-1.14.8.tar.xz'

[[user]]
id = 18
gid = 18
name = 'D-Bus Message Daemon'
login = 'messagebus'
home = '/run/dbus'
shell = '/usr/bin/false'

[[group]]
id = 18
name = 'messagebus'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                        \
            --sysconfdir=/etc                    \
            --localstatedir=/var                 \
            --runstatedir=/run                   \
            --disable-doxygen-docs               \
            --disable-xml-docs                   \
            --disable-static                     \
            --with-systemduserunitdir=no         \
            --with-systemdsystemunitdir=no       \
            --enable-user-session                \
            --docdir=/usr/share/doc/dbus-1.14.8  \
            --with-system-socket=/run/dbus/system_bus_socket

make -j$(nproc)
make DESTDIR=$OUT install

chown -v root:messagebus $OUT/usr/libexec/dbus-daemon-launch-helper &&
chmod -v      4750       $OUT/usr/libexec/dbus-daemon-launch-helper

ln -sfv /var/lib/dbus/machine-id $OUT/etc

cat > $OUT/etc/dbus-1/session-local.conf << "EOF"
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- Search for .service files in /usr/local -->
  <servicedir>/usr/local/share/dbus-1/services</servicedir>

</busconfig>
EOF

mkdir -pv $OUT/etc/systemd/system/

cat > $OUT/etc/systemd/system/dbus.service << "EOF"
[Unit]
Description=D-Bus System Message Bus
Documentation=man:dbus-daemon(1)
Requires=dbus.socket

[Service]
Type=notify
NotifyAccess=main
ExecStart=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
ExecReload=/usr/bin/dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
OOMScoreAdjust=-900
EOF

cat > $OUT/etc/systemd/system/dbus.socket << "EOF"
[Unit]
Description=D-Bus System Message Bus Socket

[Socket]
ListenStream=/run/dbus/system_bus_socket
EOF

'''
