[package]
name = 'podman'
version = '2.5.1'
description = ''
license = ''

[[source]]
source = 'https://download.savannah.gnu.org/releases/attr/attr-2.5.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/attr-2.5.1

make -j$(nproc)
make DESTDIR=$OUT install
'''
