[package]
name = 'podman'
version = '5.0.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/containers/podman/archive/refs/tags/v5.0.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

export PATH=$PATH:/usr/local/go/bin

make BUILDTAGS="selinux seccomp systemd" PREFIX=/usr
make DESTDIR=$OUT install PREFIX=/usr
'''
