[package]
name = 'gcc'
version = '13.2.0'
description = 'gcc'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

ls
cd gcc-13.2.0

case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac

mkdir -v build
cd       build

# ../libstdc++-v3/configure           \
#     --build=$(../config.guess)      \
#     --prefix=/usr                   \
#     --disable-multilib              \
#     --disable-nls                   \
#     --disable-libstdcxx-pch         

../configure --prefix=/usr            \
             LD=ld                    \
             --enable-languages=c,c++ \
             --enable-default-pie     \
             --enable-default-ssp     \
             --disable-multilib       \
             --disable-bootstrap      \
             --disable-fixincludes    \
             --with-system-zlib

make -j$(nproc)
make DESTDIR=$OUT install

ln -svr /usr/bin/cpp /usr/lib
ln -sv gcc.1 /usr/share/man/man1/cc.1

ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/13.2.0/liblto_plugin.so \
        /usr/lib/bfd-plugins/
'''
