[package]
name = 'libical'
version = '3.0.17'
description = ''
license = ''

[[source]]
source = 'https://github.com/libical/libical/releases/download/v3.0.17/libical-3.0.17.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd    build

cmake -DCMAKE_INSTALL_PREFIX=/usr  \
      -DCMAKE_BUILD_TYPE=Release   \
      -DSHARED_ONLY=yes            \
      -DICAL_BUILD_DOCS=false      \
      -DGOBJECT_INTROSPECTION=true \
      -DICAL_GLIB_VAPI=true        \
      ..

make -j1
DESTDIR=$OUT make install
'''
