[package]
name = 'libxmlb'
version = '0.3.15'
description = ''
license = ''

[[source]]
source = 'https://github.com/hughsie/libxmlb/releases/download/0.3.15/libxmlb-0.3.15.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release -Dgtkdoc=false ..

ninja
DESTDIR=$OUT ninja install
'''
