[package]
name = 'libisoburn'
version = '1.5.6'
description = ''
license = ''

[[source]]
source = 'https://files.libburnia-project.org/releases/libisoburn-1.5.6.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr              \
            --disable-static           \
            --enable-pkg-check-modules

make -j$(nproc)
make DESTDIR=$OUT install
'''
