[package]
name = 'elfutils'
version = '0.190'
description = ''
license = ''

[[source]]
source = 'https://sourceware.org/elfutils/ftp/0.190/elfutils-0.190.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --disable-static     \
            --disable-debuginfod # TODO: Should this be enabled?

make -j$(nproc)
make DESTDIR=$OUT install
'''
