[package]
name = 'xkeyboardconfig'
version = '2.41'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-2.41.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=$XORG_PREFIX --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
