[package]
name = 'libxau'
version = '1.0.11'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/pub/individual/lib/libXau-1.0.11.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure $XORG_CONFIG

make libdir=/usr/lib
make DESTDIR=$OUT install

# DESTDIR is broken for libxau, so we need to move the files manually to the correct location
# check if ${OUT}ORG_PREFIX exists
if [ -d "${OUT}ORG_PREFIX" ]; then
  mkdir -pv $OUT/usr
  mv ${OUT}ORG_PREFIX/* $OUT/usr
  rmdir ${OUT}ORG_PREFIX
fi
'''
