[package]
name = 'libxau'
version = '1.0.11'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/pub/individual/lib/libXau-1.0.11.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure $XORG_CONFIG

make libdir=$OUT/usr/lib
make DESTDIR=$OUT install
'''
