[package]
name = 'libcanberra'
version = '0.30'
description = ''
license = ''

[[source]]
source = 'https://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-oss
make

make DESTDIR=$OUT docdir=/usr/share/doc/libcanberra-0.30 install
'''
