# ! INCOMPATIBLE WITH openldap-server !
# This only has the ldap client tools, libraries and headers.
# openldap-server has the nessecary stuff for hosting an LDAP server.

[package]
name = 'openldap'
version = '2.6.7'
description = ''
license = ''

[[source]]
source = 'https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.6.7.tgz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

wget https://www.linuxfromscratch.org/patches/blfs/12.1/openldap-2.6.7-consolidated-1.patch
patch -Np1 -i ../openldap-2.6.7-consolidated-1.patch
autoconf

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --disable-static     \
            --enable-dynamic     \
            --disable-debug      \
            --disable-slapd

make depend
make -j$(nproc)
make DESTDIR=$OUT install
'''
