[package]
name = 'libidn2'
version = '2.3.7'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
