[package]
name = 'libxslt'
version = '1.1.38'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.38.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                          \
            --disable-static                       \
            --docdir=/usr/share/doc/libxslt-1.1.38 \
            PYTHON=/usr/bin/python3

make -j$(nproc)
make DESTDIR=$OUT install
'''
