[package]
name = 'xcb-util-renderutil'
version = '0.3.10'
description = ''
license = ''

[[source]]
source = 'https://xcb.freedesktop.org/dist/xcb-util-renderutil-0.3.10.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure $XORG_CONFIG

make -j$(nproc)
make DESTDIR=$OUT install
'''
