[package]
name = 'libarchive'
version = '3.7.1'
description = ''
license = ''

[[source]]
source = 'https://github.com/libarchive/libarchive/releases/download/v3.7.1/libarchive-3.7.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd libarchive-*

./configure --prefix=/usr --disable-static
make -j$(nproc)
make DESTDIR=$OUT install
'''
