[package]
name = 'libarchive'
version = '3.7.1'
description = ''
license = ''

[[source]]
source = 'https://github.com/libarchive/libarchive/releases/download/v3.7.1/libarchive-3.7.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static
make -j$(nproc)
make DESTDIR=$OUT install
'''
