[package]
name = 'sysvinit'
version = '3.07'
description = ''
license = ''

[[source]]
source = 'https://github.com/slicer69/sysvinit/releases/download/3.07/sysvinit-3.07.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

make -j$(nproc)
make DESTDIR=$OUT install
'''
