[package]
name = 'mm-common'
version = '1.0.6'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.6.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
