[package]
name = 'coreutils'
version = '9.4'
description = 'The GNU Coreutils'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://git.savannah.gnu.org/git/coreutils.git'
git_ref = 'v9.4'

[build]
script = '''
set -eux # o pipefail

./bootstrap

autoreconf -fiv
FORCE_UNSAFE_CONFIGURE=1 ./configure \
            --prefix=/usr            \
            --enable-install-program=hostname,su \
            # --enable-no-install-program=kill,uptime

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/usr/share/man/man8 $OUT/usr/sbin
mv -v $OUT/usr/bin/chroot              $OUT/usr/sbin
mv -v $OUT/usr/share/man/man1/chroot.1 $OUT/usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/'                    $OUT/usr/share/man/man8/chroot.8
'''
