[package]
name = 'inetutils'
version = '2.4'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/inetutils/inetutils-2.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr        \
            --bindir=/usr/bin    \
            --localstatedir=/var \
            --disable-logger     \
            --disable-whois      \
            --disable-rcp        \
            --disable-rexec      \
            --disable-rlogin     \
            --disable-rsh        \
            --disable-servers

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/usr/{,s}bin

mv -v $OUT/usr/{,s}bin/ifconfig
'''
