[package]
name = 'popt'
version = '1.19'
description = ''
license = ''

[[source]]
source = 'http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.19.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
