[package]
name = 'colord'
version = '1.4.7'
description = ''
license = ''

[[source]]
source = 'https://www.freedesktop.org/software/colord/releases/colord-1.4.7.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..                 \
      --prefix=/usr            \
      --buildtype=release      \
      -Ddaemon_user=colord     \
      -Dvapi=true              \
      -Dsystemd=true           \
      -Dlibcolordcompat=true   \
      -Dargyllcms_sensor=false \
      -Ddocs=false             \
      -Dman=false

ninja
DESTDIR=$OUT ninja install
'''
