# ! DEPENDS ON docbook-xml

[package]
name = 'docbook-xsl'
version = '1.79.2'
description = ''
license = ''

[[source]]
source = 'https://github.com/docbook/xslt10-stylesheets/releases/download/release/1.79.2/docbook-xsl-1.79.2.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

install -v -m755 -d $OUT/usr/share/xml/docbook/xsl-stylesheets-1.79.2 &&

cp -v -R VERSION assembly common eclipse epub epub3 extensions fo        \
         highlighting html htmlhelp images javahelp lib manpages params  \
         profiling roundtrip slides template tests tools webhelp website \
         xhtml xhtml-1_1 xhtml5                                          \
    $OUT/usr/share/xml/docbook/xsl-stylesheets-1.79.2 &&

ln -s VERSION $OUT/usr/share/xml/docbook/xsl-stylesheets-1.79.2/VERSION.xsl &&

install -v -m644 -D README \
                    $OUT/usr/share/doc/docbook-xsl-1.79.2/README.txt &&
install -v -m644    RELEASE-NOTES* NEWS* \
                    $OUT/usr/share/doc/docbook-xsl-1.79.2

if [ ! -d /etc/xml ]; then install -v -m755 -d /etc/xml; fi &&
if [ ! -f /etc/xml/catalog ]; then
    xmlcatalog --noout --create /etc/xml/catalog
fi &&

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/1.79.2" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    $OUT/etc/xml/catalog &&

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/1.79.2" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    $OUT/etc/xml/catalog &&

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    $OUT/etc/xml/catalog &&

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    $OUT/etc/xml/catalog

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook2x.sf.net/latest/xslt/man/docbook.xsl" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    $OUT/etc/xml/catalog &&

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook2x.sf.net/latest/xslt/man/docbook.xsl" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.79.2" \
    $OUT/etc/xml/catalog

'''
