[package]
name = 'cmake'
version = '3.27.2'
description = ''
license = ''

[[source]]
source = 'https://cmake.org/files/v3.27/cmake-3.27.2.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake &&

./bootstrap --prefix=/usr        \
            --system-libs        \
            --mandir=/share/man  \
            --no-system-jsoncpp  \
            --no-system-cppdap   \
            --no-system-librhash \
            --docdir=/share/doc/cmake-3.27.2

make -j$(nproc)
make DESTDIR=$OUT install
'''
