[package]
name = 'mesa'
version = '24.0.1'
description = ''
license = ''

[[source]]
source = 'https://mesa.freedesktop.org/archive/mesa-24.0.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

export PATH=$PATH:$HOME/.cargo/bin

meson setup                   \
      --prefix=$XORG_PREFIX   \
      --buildtype=release     \
      -Dplatforms=x11,wayland \
      -Dgallium-drivers=all   \
      -Dvulkan-drivers=all    \
      -Dvalgrind=disabled     \
      -Dlibunwind=disabled    \
      -Dopencl-spirv=false    \
      ..

ninja
DESTDIR=$OUT ninja install
'''

# TODO: Split mesa subprojects (such as nouveau) into separate packages
