[package]
name = 'libgudev'
version = '238'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libgudev/238/libgudev-238.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
