[package]
name = 'xmlnamespacesupport'
version = '1.09'
description = ''
license = ''

[[source]]
source = 'https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

perl Makefile.PL

make -j$(nproc)
make DESTDIR=$OUT install || true
'''
