[package]
name = 'libxml2'
version = '2.10.4'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libxml2/2.10/libxml2-2.10.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --disable-static        \
            --with-history          \
            PYTHON=/usr/bin/python3 \
            --docdir=/usr/share/doc/libxml2-2.10.4

make -j$(nproc)
make DESTDIR=$OUT install
'''
