[package]
name = 'wget'
version = '1.21.4'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr      \
            --sysconfdir=/etc  \
            --with-ssl=openssl

make -j$(nproc)
make DESTDIR=$OUT install
'''
