[package]
name = 'procps'
version = '4.0.3'
description = ''
license = ''

[[source]]
source = 'https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-4.0.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                           \
            --docdir=/usr/share/doc/procps-ng-4.0.3 \
            --disable-static                        \
            --disable-kill

make -j$(nproc)
make DESTDIR=$OUT install
'''
