[package]
name = 'geoclue'
version = '2.7.1'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/geoclue/geoclue/-/archive/2.7.1/geoclue-2.7.1.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build


meson setup --prefix=/usr       \
            --buildtype=release \
            -Dgtk-doc=false     \
            ..

ninja
DESTDIR=$OUT ninja install
'''
