[package]
name = 'accountsservice'
version = '23.13.9'
description = ''
license = ''

[[source]]
source = 'https://www.freedesktop.org/software/accountsservice/accountsservice-23.13.9.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Dadmin_group=adm

ninja
DESTDIR=$OUT ninja install

mkdir -pv $OUT/etc/polkit-1/rules.d/

cat > $OUT/etc/polkit-1/rules.d/40-adm.rules << "EOF"
polkit.addAdminRule(function(action, subject) {
   return ["unix-group:adm"];
   });
EOF
'''
