[package]
name = 'glib'
version = '2.78.4'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/glib/2.78/glib-2.78.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd glib-*

export PATH=$PATH:/usr/lib/python3.11/site-packages/bin

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Dman=true

ninja

DESTDIR=$OUT ninja install
'''
