[package]
name = 'glib'
version = '2.76.4'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/glib/2.76/glib-2.76.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd glib-*

export PATH=$PATH:/usr/lib/python3.11/site-packages/bin

meson _build
ninja -C _build
DESTDIR=$OUT ninja -C _build install
'''
