[package]
name = 'icu'
version = '74.2'
description = ''
license = ''

[[source]]
source = 'https://github.com/unicode-org/icu.git'
git_ref = 'release-74-2'

[build]
script = '''
set -eux # o pipefail

mkdir icu4c-build
cd icu4c-build

../icu4c/source/runConfigureICU Linux --prefix=/usr

make
make DESTDIR=$OUT install

'''
