[package]
name = 'make-ca'
version = '1.13.0'
description = 'make-ca'
license = ''

[[source]]
source = 'https://github.com/lfs-book/make-ca/releases/download/v1.13/make-ca-1.13.tar.xz'

# https://www.linuxfromscratch.org/blfs/view/svn/postlfs/make-ca.html

[build]
script = '''
set -eux # o pipefail

ls
cd make-ca-1.13

mkdir $OUT/tmp

make DESTDIR=$OUT install &&
install -vdm755 $OUT/etc/ssl/local

# replace #!/bin/bash with #!/bin/sh
sed -i 's|#!/bin/bash|#!/bin/sh|' $OUT/usr/sbin/make-ca

# run make-ca -g to generate the certificates inside of chroot to prevent messing up the host
# chmod +x $OUT/usr/libexec/make-ca
chroot $OUT /usr/libexec/make-ca -g || true

cat > $OUT/etc/cron.weekly/update-pki.sh << "EOF" &&
#!/bin/bash
/usr/sbin/make-ca -g
EOF
chmod 754 $OUT/etc/cron.weekly/update-pki.sh

mkdir -pv $OUT/etc/profile.d &&
cat > $OUT/etc/profile.d/pythoncerts.sh << "EOF"
# Begin /etc/profile.d/pythoncerts.sh

export _PIP_STANDALONE_CERT=/etc/pki/tls/certs/ca-bundle.crt

# End /etc/profile.d/pythoncerts.sh
EOF

'''
