[package]
name = 'make-ca'
version = '1.13.0'
description = 'make-ca'
license = ''

[[source]]
source = 'https://github.com/lfs-book/make-ca/releases/download/v1.13/make-ca-1.13.tar.xz'

# https://www.linuxfromscratch.org/blfs/view/svn/postlfs/make-ca.html

[build]
script = '''
set -eux # o pipefail

ls
cd make-ca-1.13

make install &&
install -vdm755 /etc/ssl/local
/usr/sbin/make-ca -g

cat > /etc/cron.weekly/update-pki.sh << "EOF" &&
#!/bin/bash
/usr/sbin/make-ca -g
EOF
chmod 754 /etc/cron.weekly/update-pki.sh

mkdir -pv /etc/profile.d &&
cat > /etc/profile.d/pythoncerts.sh << "EOF"
# Begin /etc/profile.d/pythoncerts.sh

export _PIP_STANDALONE_CERT=/etc/pki/tls/certs/ca-bundle.crt

# End /etc/profile.d/pythoncerts.sh
EOF

'''
