[package]
name = 'dconf'
version = '45.0.1'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/dconf-editor/45/dconf-editor-45.0.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

echo "echo fake update-desktop-database ran" > /usr/bin/update-desktop-database
chmod +x /usr/bin/update-desktop-database

mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release ..
DESTDIR=$OUT ninja
DESTDIR=$OUT ninja install
'''
