[package]
name = 'zlib'
version = '1.3'
description = 'zlib'
license = ''

[[source]]
source = 'https://www.zlib.net/zlib-1.3.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd zlib-1.3

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install

rm -fv $OUT/usr/lib/libz.a
'''
