[package]
name = 'nettle'
version = '3.9.1'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/nettle/nettle-3.9.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
