[package]
name = 'glibc'
version = '2.38'
description = 'The GNU C Library'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://sourceware.org/git/glibc.git'
git_ref = 'release/2.38/master'

[build]
script = '''
set -eux # o pipefail

mkdir -v build
cd build

echo "rootsbindir=/usr/sbin" > configparms

../configure                             \
      --prefix=/lib     \
      --build=$(../scripts/config.guess) \
      --enable-kernel=4.14               \
      libc_cv_slibdir=/usr/lib

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/lib64 $OUT/usr/bin

case $(uname -m) in
    i?86)   ln -sfv ld-linux.so.2 $OUT/lib/ld-lsb.so.3
    ;;
    x86_64) ln -sfv $OUT/lib/ld-linux-x86-64.so.2 $OUT/lib64/ld-linux-x86-64.so.2
            ln -sfv $OUT/lib/ld-linux-x86-64.so.2 $OUT/lib64/ld-lsb-x86-64.so.3
            ln -sfv $OUT/lib/ld-linux-x86-64.so.2 $OUT/lib/ld-linux.so.2
            ln -sfv $OUT/lib/ld-linux-x86-64.so.2 $OUT/lib/ld.so
            ln -sfv $OUT/lib/ld-linux-x86-64.so.2 $OUT/usr/bin/ld.so
    ;;
esac

cat > $OUT/etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
/lib
/usr/lib

EOF
'''
