[package]
name = 'glibc'
version = '2.38'
description = 'The GNU C Library'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://sourceware.org/git/glibc.git'
git_ref = 'release/2.38/master'

[build]
script = '''
set -eux # o pipefail

mkdir -v build
cd build

echo "rootsbindir=/usr/sbin" > configparms

../configure                             \
      --prefix=/usr                      \
      --build=$(../scripts/config.guess) \
      --enable-kernel=4.14               \
      libc_cv_slibdir=/usr/lib

make -j$(nproc)
make DESTDIR=$OUT install

case $(uname -m) in
    i?86)   ln -sfv ld-linux.so.2 $OUT/lib/ld-lsb.so.3
    ;;
    x86_64) ln -sfv ../lib/ld-linux-x86-64.so.2 $OUT/lib64
            ln -sfv ../lib/ld-linux-x86-64.so.2 $OUT/lib64/ld-lsb-x86-64.so.3
    ;;
esac
'''
