[package]
name = 'libcap'
version = '1.2.69'
description = 'libcap2'
license = ''

[[source]]
source = 'https://git.kernel.org/pub/scm/libs/libcap/libcap.git'
git_ref = 'v1.2.69'

[build]
script = '''
set -eux # o pipefail

make lib=usr/lib -j$(nproc)
make DESTDIR=$OUT lib=usr/lib install

chmod -v 755 $OUT/usr/lib/libcap.so.2.69
'''
