[package]
name = 'kbd'
version = '2.6.1'
description = ''
license = ''

[[source]]
source = 'https://www.kernel.org/pub/linux/utils/kbd/kbd-2.6.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

./configure --prefix=/usr --disable-vlock

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/usr/share/doc/kbd-2.6.1

cp -R -v docs/doc -T $OUT/usr/share/doc/kbd-2.6.1
'''
