[package]
name = 'libhandy'
version = '1.8.3'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libhandy/1.8/libhandy-1.8.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
