[package]
name = 'xmlsaxbase'
version = '1.09'
description = ''
license = ''

[[source]]
source = 'https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-Base-1.09.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

perl Makefile.PL

make -j$(nproc)
make DESTDIR=$OUT install || true
'''
