[package]
name = 'intltool'
version = '0.51.0'
description = ''
license = ''

[[source]]
source = 'https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i 's:\\\${:\\\$\\{:' intltool-update.in

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install

install -v -Dm644 doc/I18N-HOWTO $OUT/usr/share/doc/intltool-0.51.0/I18N-HOWTO
'''
