[package]
name = 'curl'
version = '8.4.0'
description = 'curl'
license = ''

[[source]]
source = 'https://curl.se/download/curl-8.4.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd curl-8.4.0

./configure --prefix=/usr                           \
            --disable-static                        \
            --with-openssl                          \
            --enable-threaded-resolver              \
            --with-ca-path=/etc/ssl/certs

make -j$(nproc)
make DESTDIR=$OUT install
'''
