[package]
name = 'mpc'
version = '1.3.1'
description = 'mpc'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-1.3.1

make -j$(nproc)
make DESTDIR=$OUT install
'''
