[package]
name = 'ntp'
version = '4.2.8p17'
description = ''
license = ''

[[source]]
source = 'https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/ntp-4.2.8p17.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr         \
            --bindir=/usr/sbin    \
            --sysconfdir=/etc     \
            --enable-linuxcaps    \
            --with-lineeditlibs=readline \
            --docdir=/usr/share/doc/ntp-4.2.8p17

make -j$(nproc)
make DESTDIR=$OUT install
'''
