[package]
name = 'ntp'
version = '4.2.8p17'
description = ''
license = ''

[[source]]
source = 'https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/ntp-4.2.8p17.tar.gz'

[[user]]
id = 87
gid = 87
name = 'Network Time Protocol Daemon'
login = 'ntp'
home = '/var/lib/ntp'
shell = '/usr/bin/false'

[[group]]
id = 87
name = 'ntp'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr         \
            --bindir=/usr/sbin    \
            --sysconfdir=/etc     \
            --enable-linuxcaps    \
            --with-lineeditlibs=readline \
            --docdir=/usr/share/doc/ntp-4.2.8p17

make -j$(nproc)
make DESTDIR=$OUT install

# ntp daemon home dir
install -v -o 87 -g 87 -d $OUT/var/lib/ntp
'''
