[package]
name = 'spirv-llvm-translator'
version = '18.1.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v18.1.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

cmake .. -DLLVM_DIR=/usr/lib/cmake/llvm/
make llvm-spirv -j`nproc`
make DESTDIR=$OUT install
'''
