[package]
name = 'gnutls'
version = '3.8.3'
description = ''
license = ''

[[source]]
source = 'https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-3.8.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr \
            --docdir=/usr/share/doc/gnutls-3.8.3 \
            --with-default-trust-store-pkcs11="pkcs11:"

make -j$(nproc)
make DESTDIR=$OUT install
'''
