[package]
name = 'automake'
version = '1.16.5'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.16.5

make -j$(nproc)
make DESTDIR=$OUT install
'''
