[package]
name = 'openssh'
version = '9.6p1'
description = ''
license = ''

[[source]]
source = 'https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.6p1.tar.gz'

[[user]]
id = 50
gid = 50
name = 'sshd daemon'
login = 'sshd'
home = '/var/lib/sshd'
shell = '/usr/bin/false'

[[group]]
id = 50
name = 'sshd'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                            \
            --sysconfdir=/etc/ssh                    \
            --with-privsep-path=/var/lib/sshd        \
            --with-default-path=/usr/bin             \
            --with-superuser-path=/usr/sbin:/usr/bin \
            --with-pid-dir=/run

make -j$(nproc)
make DESTDIR=$OUT install

# sshd home dir
install -v -g sys -m700 -d $OUT/var/lib/sshd
'''
