[package]
name = 'bash-completion'
version = '2.11'
description = ''
license = ''

[[source]]
source = 'https://github.com/scop/bash-completion/releases/download/2.11/bash-completion-2.11.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure

make -j$(nproc)
make DESTDIR=$OUT install
'''
