[package]
name = 'fontconfig'
version = '2.13.0'
description = ''
license = ''

[[source]]
source = 'https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.0.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-docs       \
            --docdir=/usr/share/doc/fontconfig-2.13.0

make -j$(nproc)
make DESTDIR=$OUT install

install -v -dm755 \
        $OUT/usr/share/{man/man{1,3,5},doc/fontconfig-2.13.0/fontconfig-devel}
install -v -m644 fc-*/*.1         $OUT/usr/share/man/man1
install -v -m644 doc/*.3          $OUT/usr/share/man/man3
install -v -m644 doc/fonts-conf.5 $OUT/usr/share/man/man5
install -v -m644 doc/fontconfig-devel/* \
                                  $OUT/usr/share/doc/fontconfig-2.13.0/fontconfig-devel
install -v -m644 doc/*.{pdf,sgml,txt,html} \
                                  $OUT/usr/share/doc/fontconfig-2.13.0

'''
