[package]
name = 'dracut'
version = '060'
description = 'The Bourne Again SHell'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://github.com/dracutdevs/dracut.git'
git_ref = 'master'
# commit followed release process but isn't tagged, see https://github.com/dracutdevs/dracut/discussions/2584
git_commit = '856e7ac'

[build]
script = '''
set -eux # o pipefail

./configure --prefix=/usr --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
