[package]
name = 'acl'
version = '2.3.1'
description = ''
license = ''

[[source]]
source = 'https://download.savannah.gnu.org/releases/acl/acl-2.3.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr         \
            --disable-static      \
            --docdir=/usr/share/doc/acl-2.3.1

make -j$(nproc)
make DESTDIR=$OUT install
'''
