[package]
name = 'gnome-desktop'
version = '44.0'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gnome-desktop/44/gnome-desktop-44.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr       \
            --buildtype=release \
            ..

ninja
DESTDIR=$OUT ninja install
'''
