[package]
name = 'bison'
version = '3.8.2'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2

make -j$(nproc)
make DESTDIR=$OUT install
'''
