[package]
name = 'gst-plugins-bad'
version = '1.22.10'
description = ''
license = ''

[[source]]
source = 'https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.22.10.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson  setup ..            \
       --prefix=/usr       \
       --buildtype=release \
       -Dgpl=enabled       \
       -Dpackage-origin=https://github.com/stable-os/packages \
       -Dpackage-name="GStreamer 1.22.10"

ninja
DESTDIR=$OUT ninja install
'''
