[package]
name = 'audit'
version = '3.1.2'
description = ''
license = ''

[[source]]
source = 'https://github.com/linux-audit/audit-userspace/archive/refs/tags/v3.1.2.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --with-gnu-ld

make -j$(nproc)
make DESTDIR=$OUT install
'''
