[package]
name = 'libxcrypt'
version = '4.4.36'
description = ''
license = ''

[[source]]
source = 'https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=no     \
            --disable-static             \
            --disable-failure-tokens

make -j$(nproc)
make DESTDIR=$OUT install

# Legacy compatibility
make distclean
./configure --prefix=/usr                \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=glibc  \
            --disable-static             \
            --disable-failure-tokens
make -j$(nproc)
cp -av .libs/libcrypt.so.1* $OUT/usr/lib
'''
