[package]
name = 'pkg-builder'
version = '0.1.0'
description = 'StableOS Package Builder'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://github.com/stable-os/pkg-builder.git'
git_ref = 'main'

[build]
script = '''
set -eux # o pipefail

$HOME/.cargo/bin/cargo build --release
mkdir -p $OUT/usr/bin
cp target/release/pkg-builder $OUT/usr/bin
'''
