[package]
name = 'drawves'
version = '1.24.0'
description = 'git'
license = ''

[[source]]
source = 'https://github.com/acmel/dwarves.git'
git_ref = 'v1.24'

[build]
script = '''
set -eux # o pipefail

git submodule update --init --recursive

cmake -DCMAKE_INSTALL_PREFIX=/usr

make DESTDIR=$OUT install
'''
