[package]
name = 'gnupg'
version = '2.4.4'
description = ''
license = ''

[[source]]
source = 'https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-2.4.4.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

../configure --prefix=/usr           \
             --localstatedir=/var    \
             --sysconfdir=/etc       \
             --docdir=/usr/share/doc/gnupg-2.4.4

make -j$(nproc)
make DESTDIR=$OUT install
'''
