[package]
name = 'slang'
version = '2.3.3'
description = ''
license = ''

[[source]]
source = 'https://www.jedsoft.org/releases/slang/slang-2.3.3.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-readline=gnu

make -j1
make install_doc_dir=/usr/share/doc/slang-2.3.3   \
     SLSH_DOC_DIR=/usr/share/doc/slang-2.3.3/slsh \
     DESTDIR=$OUT                                 \
     install
'''
