[package]
name = 'mutter'
version = '45.4'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/mutter/45/mutter-45.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr              \
            --buildtype=release        \
            -Dtests=false              \
            -Dprofiler=false           \
            ..

ninja
DESTDIR=$OUT ninja install
'''
