[package]
name = 'essential-files'
version = '0.1.0'
description = 'Essential system files'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://github.com/stable-os/packages.git'
git_ref = 'main'

[[user]]
id = 0
gid = 0
name = 'Administrator (root)'
login = 'root'
home = '/root'
shell = '/usr/bin/bash'

[[user]]
id = 1
gid = 1
name = 'bin'
login = 'bin'
home = '/dev/null'
shell = '/usr/bin/false'

[[user]]
id = 6
gid = 6
name = 'Daemon User'
login = 'daemon'
home = '/dev/null'
shell = '/usr/bin/false'

[[user]]
id = 65543
gid = 65543
name = 'Unprivileged User'
login = 'nobody'
home = '/dev/null'
shell = '/usr/bin/false'

[[group]]
id = 0
name = "root"

[[group]]
id = 1
name = "bin"

[[group]]
id = 2
name = "sys"

[[group]]
id = 3
name = "kmem"

[[group]]
id = 4
name = "tape"

[[group]]
id = 5
name = "tty"

[[group]]
id = 6
name = "daemon"

[[group]]
id = 7
name = "floppy"

[[group]]
id = 8
name = "disk"

[[group]]
id = 9
name = "lp"

[[group]]
id = 10
name = "dialout"

[[group]]
id = 11
name = "audio"

[[group]]
id = 12
name = "video"

[[group]]
id = 13
name = "utmp"

[[group]]
id = 14
name = "dailout"

[[group]]
id = 15
name = "cdrom"

[[group]]
id = 16
name = "adm"

[[group]]
id = 17
name = "render"

[[group]]
id = 20
name = "sgx"

[[group]]
id = 24
name = "input"

[[group]]
id = 34
name = "mail"

[[group]]
id = 61
name = "kvm"

[[group]]
id = 97
name = "wheel"

[[group]]
id = 999
name = "users"

[[group]]
id = 65534
name = "nogroup"

[build]
script = '''
set -eux # o pipefail

mkdir -pv $OUT/etc/ $OUT/var/log

touch $OUT/etc/{passwd,group}

# TODO: Add a way to specify the hostname on new systems, installer or oobe?

cat > $OUT/etc/hosts << EOF
127.0.0.1  localhost
::1        localhost
EOF

cat > $OUT/etc/os-release << "EOF"
NAME="from os-release file"
VERSION="0"
ID=lfs
PRETTY_NAME="from os-release file"
VERSION_CODENAME="from-os-release-file"
EOF

touch $OUT/var/log/{btmp,lastlog,faillog,wtmp}
# chgrp -v utmp $OUT/var/log/lastlog
chmod -v 664  $OUT/var/log/lastlog
chmod -v 600  $OUT/var/log/btmp

mkdir -pv $OUT/etc/profile.d/
cat > $OUT/etc/profile.d/init.sh << "EOF"
set +h
umask 022

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/x86_64-pc-linux-gnu/bin/:/usr/lib/python3.11/site-packages/bin/:/usr/local/bin/
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig
ACLOCAL_PATH=/usr/share/aclocal
XORG_PREFIX=/usr
export PKG_CONFIG_PATH PATH ACLOCAL_PATH XORG_PREFIX

EOF

mkdir -pv $OUT/root/
cat > $OUT/root/.bashrc << "EOF"
set +h
umask 022

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/x86_64-pc-linux-gnu/bin/:/usr/lib/python3.11/site-packages/bin/:/usr/local/bin/
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig
ACLOCAL_PATH=/usr/share/aclocal
XORG_PREFIX=/usr
export PKG_CONFIG_PATH PATH ACLOCAL_PATH XORG_PREFIX

EOF
'''
