[package]
name = 'essential-files'
version = '0.1.0'
description = 'Essential system files'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://github.com/stable-os/packages.git'
git_ref = 'main'

[build]
script = '''
set -eux # o pipefail

mkdir -pv $OUT/etc/ $OUT/var/log

# TODO: Add a way to specify the hostname on new systems, installer or oobe?

cat > $OUT/etc/hosts << EOF
127.0.0.1  localhost
::1        localhost
EOF

cat > $OUT/etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/usr/bin/false
daemon:x:6:6:Daemon User:/dev/null:/usr/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/run/dbus:/usr/bin/false
uuidd:x:80:80:UUID Generation Daemon User:/dev/null:/usr/bin/false
nobody:x:65534:65534:Unprivileged User:/dev/null:/usr/bin/false
EOF

cat > $OUT/etc/group << "EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
input:x:24:
mail:x:34:
kvm:x:61:
uuidd:x:80:
wheel:x:97:
users:x:999:
nogroup:x:65534:
EOF

cat > $OUT/etc/os-release << "EOF"
NAME="from os-release file"
VERSION="0"
ID=lfs
PRETTY_NAME="from os-release file"
VERSION_CODENAME="from-os-release-file"
EOF

touch $OUT/var/log/{btmp,lastlog,faillog,wtmp}
# chgrp -v utmp $OUT/var/log/lastlog
chmod -v 664  $OUT/var/log/lastlog
chmod -v 600  $OUT/var/log/btmp

mkdir -pv $OUT/etc/profile.d/
cat > $OUT/etc/profile.d/init.sh << "EOF"
set +h
umask 022

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/x86_64-pc-linux-gnu/bin/:/usr/lib/python3.11/site-packages/bin/:/usr/local/bin/
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig
ACLOCAL_PATH=/usr/share/aclocal
export PKG_CONFIG_PATH PATH ACLOCAL_PATH

EOF

mkdir -pv $OUT/root/
cat > $OUT/root/.bashrc << "EOF"
set +h
umask 022

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/x86_64-pc-linux-gnu/bin/:/usr/lib/python3.11/site-packages/bin/:/usr/local/bin/
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig
ACLOCAL_PATH=/usr/share/aclocal
export PKG_CONFIG_PATH PATH ACLOCAL_PATH

EOF
'''
