[package]
name = 'hatchling'
version = '1.21.0'
description = ''
license = ''

[[source]]
source = 'https://files.pythonhosted.org/packages/fd/4a/8196e79c0d6e5eb10436dd2fcccc889a76af6ecf9bc35f87408159497d4d/hatchling-1.21.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --target=$OUT/usr/lib/python3.11/site-packages --find-links=dist hatchling
'''
