[package]
name = 'xorg-input-synaptics'
version = '1.9.2'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/archive/individual/driver/xf86-input-synaptics-1.9.2.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
