[package]
name = 'libgusb'
version = '0.4.8'
description = ''
license = ''

[[source]]
source = 'https://github.com/hughsie/libgusb/releases/download/0.4.8/libgusb-0.4.8.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Ddocs=false

ninja
DESTDIR=$OUT ninja install
'''
