[package]
name = 'pkgconf'
version = '2.0.1'
description = ''
license = ''

[[source]]
source = 'https://distfiles.ariadne.space/pkgconf/pkgconf-2.0.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr              \
            --disable-static           \
            --docdir=/usr/share/doc/pkgconf-2.0.1

make -j$(nproc)
make DESTDIR=$OUT install

ln -sv pkgconf   /usr/bin/pkg-config || true
ln -sv pkgconf.1 /usr/share/man/man1/pkg-config.1 || true
'''
