[package]
name = 'libsigc'
version = '2.12.1'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libsigc++/2.12/libsigc++-2.12.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir bld
cd bld

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
