[package]
name = 'jinja2'
version = '1.11.1'
description = ''
license = ''

[[source]]
source = 'https://github.com/ninja-build/ninja/archive/v1.11.1/ninja-1.11.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --no-user --target=$OUT/usr/lib/python3.11/site-packages --find-links dist Jinja2
'''
