[package]
name = 'iniconfig'
version = '2.0.0'
description = ''
license = ''

[[source]]
source = 'https://files.pythonhosted.org/packages/d7/4b/cbd8e699e64a6f16ca3a8220661b5f83792b3017d0f79807cb8708d33913/iniconfig-2.0.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --target=$OUT/usr/lib/python3.11/site-packages --find-links=dist iniconfig
'''
