[package]
name = 'libpgpme'
version = '1.21.0'
description = ''
license = ''

[[source]]
source = 'https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.21.0.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-gpg-test

make -j$(nproc)
make DESTDIR=$OUT install
'''
