[package]
name = 'ucd'
version = '15.1.0'
description = ''
license = ''

[[source]]
source = 'https://www.unicode.org/Public/zipped/15.1.0/UCD.zip'

[build]
script = '''
set -eux # o pipefail

mkdir -p $OUT/usr/share/unicode/ucd
mv $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1) $OUT/usr/share/unicode/ucd
'''
