[package]
name = 'ucd'
version = '15.1.0'
description = ''
license = ''

[[source]]
source = 'https://www.unicode.org/Public/zipped/15.1.0/UCD.zip'

[build]
script = '''
set -eux # o pipefail

ls -lha

mkdir -pv $OUT/usr/share/unicode
mv UCD $OUT/usr/share/unicode/ucd
'''
