[package]
name = 'alsa-lib'
version = '1.2.11'
description = ''
license = ''

[[source]]
source = 'https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.11.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
