[package]
name = 'readline'
version = '8.2.0'
description = 'readline'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd readline-8.2

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

mv /usr/lib/libreadline.so.8 /usr/lib/_libreadline.so.8

./configure --prefix=/usr    \
            --disable-static \
            --with-curses    \
            --docdir=/usr/share/doc/readline-8.2

make SHLIB_LIBS="-lncursesw"
make SHLIB_LIBS="-lncursesw" DESTDIR=$OUT install

mv /usr/lib/_libreadline.so.8 /usr/lib/libreadline.so.8

install -v -m644 doc/*.{ps,pdf,html,dvi} $OUT/usr/share/doc/readline-8.2
'''
