[package]
name = 'gdk-pixbuf'
version = '2.42.10'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.10.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      --wrap-mode=nofallback

ninja
DESTDIR=$OUT ninja install
'''
