[package]
name = 'libnl'
version = '3.9.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/thom311/libnl/releases/download/libnl3_9_0/libnl-3.9.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
