[package]
name = 'ninja'
version = '1.11.1'
description = ''
license = ''

[[source]]
source = 'https://github.com/ninja-build/ninja/archive/v1.11.1/ninja-1.11.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

python3 configure.py --bootstrap

mkdir -pv $OUT/usr/bin/ $OUT/usr/share/bash-completion/completions/ $OUT/usr/share/zsh/site-functions/

install -vm755 ninja $OUT/usr/bin/
install -vDm644 misc/bash-completion $OUT/usr/share/bash-completion/completions/ninja
install -vDm644 misc/zsh-completion  $OUT/usr/share/zsh/site-functions/_ninja
'''
