[package]
name = 'tar'
version = '1.35'
description = 'tar'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

export FORCE_UNSAFE_CONFIGURE=1

./configure --prefix=/usr                     \
            --build=$(build-aux/config.guess)
make -j$(nproc)
make DESTDIR=$OUT install
'''
