[package]
name = 'yajl1'
version = '1.0.12'
description = ''
license = ''

[[source]]
source = 'https://github.com/lloyd/yajl/archive/refs/tags/1.0.12.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix /usr

make
make DESTDIR=$OUT install
'''
