[package]
name = 'mpc'
version = '1.3.1'
description = 'mpc'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd mpfr-4.2.1

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-1.3.1

make
make DESTDIR=$OUT install
'''
