[package]
name = 'meson'
version = '10.2.0'
description = 'readline'
license = ''

[[source]]
source = 'https://github.com/mesonbuild/meson/releases/download/1.2.1/meson-1.2.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd asciidoc-*

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --target=$OUT/usr/lib/python3.11/site-packages --find-links dist meson

install -vDm644 data/shell-completions/bash/meson $OUT/usr/share/bash-completion/completions/meson
install -vDm644 data/shell-completions/zsh/_meson $OUT/usr/share/zsh/site-functions/_meson
'''
