[package]
name = 'libpng'
version = '1.6.42'
description = ''
license = ''

[[source]]
source = 'https://downloads.sourceforge.net/libpng/libpng-1.6.42.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

wget https://downloads.sourceforge.net/sourceforge/libpng-apng/libpng-1.6.40-apng.patch.gz
gzip -cd ../libpng-1.6.40-apng.patch.gz | patch -p1

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
