[package]
name = 'libadwaita'
version = '1.4.3'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libadwaita/1.4/libadwaita-1.4.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
