[package]
name = 'mobile-broadband-provider-info'
version = '20230416'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/mobile-broadband-provider-info/20230416/mobile-broadband-provider-info-20230416.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
