[package]
name = 'gdm'
version = '45.0.1'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gdm/45/gdm-45.0.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Dgdm-xsession=true \
      -Drun-dir=/run/gdm

ninja
DESTDIR=$OUT ninja install
'''
