[package]
name = 'gdm'
version = '45.0.1'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gdm/45/gdm-45.0.1.tar.xz'

[[user]]
id = 21
gid = 21
name = 'GNOME Display Manager Daemon'
login = 'gdm'
home = '/var/lib/gdm'
shell = '/usr/bin/false'

[[group]]
id = 21
name = 'gdm'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Dgdm-xsession=true \
      -Drun-dir=/run/gdm

ninja
DESTDIR=$OUT ninja install
'''
