[package]
name = 'ruby'
version = '3.3.0'
description = ''
license = ''

[[source]]
source = 'https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr         \
            --disable-rpath       \
            --enable-shared       \
            --without-valgrind    \
            --without-baseruby    \
            ac_cv_func_qsort_r=no \
            --docdir=/usr/share/doc/ruby-3.3.0

make -j$(nproc)
make DESTDIR=$OUT install
'''
