[package]
name = 'upower'
version = '1.90.2'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/upower/upower/-/archive/v1.90.2/upower-v1.90.2.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..                  \
      --prefix=/usr             \
      --buildtype=release       \
      -Dgtk-doc=false           \
      -Dman=false               \
      -Dsystemdsystemunitdir=no \
      -Dudevrulesdir=/usr/lib/udev/rules.d

ninja
DESTDIR=$OUT ninja install
'''
