[package]
name = 'pipewire'
version = '1.0.3'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/1.0.3/pipewire-1.0.3.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..                \
      --prefix=/usr           \
      --buildtype=release     \
      -Dsession-managers="[]"

ninja
DESTDIR=$OUT ninja install
'''
