[package]
name = 'xorg-video-mach64'
version = '6.9.7'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/archive/individual/driver/xf86-video-mach64-6.9.7.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
