[package]
name = 'atkmm'
version = '2.28.4'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/atkmm/2.28/atkmm-2.28.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release -Dbuild-documentation=false ..

ninja
DESTDIR=$OUT ninja install
'''
