[package]
name = 'spirv-headers'
version = '1.3.280.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-1.3.280.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

cmake -G Ninja ..

ninja
DESTDIR=$OUT ninja install
'''
