[package]
name = 'nghttp2'
version = '1.55.1'
description = ''
license = ''

[[source]]
source = 'https://github.com/nghttp2/nghttp2/releases/download/v1.55.1/nghttp2-1.55.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --disable-static  \
            --enable-lib-only \
            --docdir=/usr/share/doc/nghttp2-1.55.1

make -j$(nproc)
make DESTDIR=$OUT install
'''
