[package]
name = 'pyparsing'
version = '3.1.1'
description = ''
license = ''

[[source]]
source = 'https://files.pythonhosted.org/packages/source/p/pyparsing/pyparsing-3.1.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --target=$OUT/usr/lib/python3.11/site-packages --find-links=dist pyparsing
'''
