[package]
name = 'avahi'
version = '0.8'
description = ''
license = ''

[[source]]
source = 'https://github.com/lathiat/avahi/releases/download/v0.8/avahi-0.8.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure \
    --prefix=/usr                  \
    --sysconfdir=/etc              \
    --localstatedir=/var           \
    --disable-static               \
    --disable-libevent             \
    --disable-mono                 \
    --disable-monodoc              \
    --disable-python               \
    --disable-qt3                  \
    --disable-qt4                  \
    --disable-qt5                  \
    --enable-core-docs             \
    --with-distro=none             \
    --with-systemdsystemunitdir=no \
    --with-dbus-system-address='unix:path=/run/dbus/system_bus_socket'

make -j$(nproc)
make DESTDIR=$OUT install

install -v -m644 -D README $OUT/usr/share/doc/libgpg-error-1.47/README
'''
