[package]
name = 'xcb-proto'
version = '1.16.0'
description = ''
license = ''

[[source]]
source = 'https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.16.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

PYTHON=python3 ./configure $XORG_CONFIG

make DESTDIR=$OUT install
'''
