[package]
name = 'xcb-proto'
version = '1.16.0'
description = ''
license = ''

[[source]]
source = 'https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.16.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

PYTHON=python3 ./configure $XORG_CONFIG

make DESTDIR=$OUT install

# DESTDIR is broken for xcb-proto, so we need to move the files manually to the correct location
# check if ${OUT}ORG_PREFIX exists
if [ -d "${OUT}ORG_PREFIX" ]; then
  mv ${OUT}ORG_PREFIX/* $OUT
  rmdir ${OUT}ORG_PREFIX
fi
'''
