[package]
name = 'exempi'
version = '2.6.5'
description = ''
license = ''

[[source]]
source = 'https://libopenraw.freedesktop.org/download/exempi-2.6.5.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
