[package]
name = 'xz'
version = '5.4.4'
description = 'xz'
license = ''

[[source]]
source = 'https://tukaani.org/xz/xz-5.4.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.4.4

make -j$(nproc)
make DESTDIR=$OUT install
'''
