[package]
name = 'libwnck'
version = '43.0'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libwnck/43/libwnck-43.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd    build

meson setup --prefix=/usr --buildtype=release ..
ninja

ninja DESTDIR=$OUT install
'''
