[package]
name = 'gcr3'
version = '3.41.2'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gcr/3.41/gcr-3.41.2.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i 's:"/desktop:"/org:' schema/*.xml

mkdir build
cd build

meson setup --prefix=/usr       \
            --buildtype=release \
            -Dgtk_doc=false     \
            ..

ninja
DESTDIR=$OUT ninja install
'''
