[package]
name = 'vim'
version = '9.0.1677'
description = ''
license = ''

[[source]]
source = 'https://anduin.linuxfromscratch.org/LFS/vim-9.0.1677.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

echo '#define SYS_VIMRC_FILE  "/etc/vimrc"' >>  src/feature.h
echo '#define SYS_GVIMRC_FILE "/etc/gvimrc"' >> src/feature.h

./configure --prefix=/usr --without-x --enable-gui=no --with-features=huge --with-tlib=ncursesw

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/usr/share/doc/ $OUT/usr/share/man/ $OUT/usr/bin/

ln -sv vim $OUT/usr/bin/vi
for L in  $OUT/usr/share/man/{,*/}man1/vim.1; do
    ln -sv vim.1 $(dirname $L)/vi.1
done

ln -sv ../vim/vim90/doc $OUT/usr/share/doc/vim-9.0.1677
'''
