[package]
name = 'm4'
version = '1.4.19'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install
'''
