[package]
name = 'gtk4'
version = '4.12.5'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gtk/4.12/gtk-4.12.5.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd    build

meson setup --prefix=/usr           \
            --buildtype=release     \
            -Dbroadway-backend=true \
            -Dintrospection=enabled \
            ..

ninja
DESTDIR=$OUT ninja install
'''
