[package]
name = 'libburn'
version = '1.5.6'
description = ''
license = ''

[[source]]
source = 'https://files.libburnia-project.org/releases/libburn-1.5.6.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
