[package]
name = 'newt'
version = '0.52.24'
description = ''
license = ''

[[source]]
source = 'https://releases.pagure.org/newt/newt-0.52.24.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -e '/install -m 644 $(LIBNEWT)/ s/^/#/' \
    -e '/$(LIBNEWT):/,/rv/ s/^/#/'          \
    -e 's/$(LIBNEWT)/$(LIBNEWTSH)/g'        \
    -i Makefile.in

./configure --prefix=/usr           \
            --with-gpm-support      \
            --with-python=python3.11

make -j$(nproc)
make DESTDIR=$OUT install
'''
