[package]
name = 'npth'
version = '1.6'
description = ''
license = ''

[[source]]
source = 'https://www.gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install
'''
