[package]
name = 'polkit'
version = '124'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/polkit/polkit/-/archive/124/polkit-124.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..                            \
      --prefix=/usr                       \
      --buildtype=release                 \
      -Dman=true                          \
      -Dsession_tracking=libsystemd-login \
      -Dtests=true

ninja
DESTDIR=$OUT ninja install
'''
