[package]
name = 'freetype'
version = '2.13.2'
description = ''
license = ''

[[source]]
source = 'https://downloads.sourceforge.net/freetype/freetype-2.13.2.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg &&

sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
    -i include/freetype/config/ftoption.h  &&

./configure --prefix=/usr --enable-freetype-config --disable-static

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -p $OUT/usr/bin
cp builds/unix/freetype-config $OUT/usr/bin
'''
