[package]
name = 'libshumate'
version = '1.1.3'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libshumate/1.1/libshumate-1.1.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd    build

meson setup --prefix=/usr          \
            --buildtype=release    \
            --wrap-mode=nodownload \
            -Dgtk_doc=false        \
            ..
ninja

ninja DESTDIR=$OUT install
'''
