[package]
name = 'shared-mime-info'
version = '2.4'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.4/shared-mime-info-2.4.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release -Dupdate-mimedb=true ..

ninja
DESTDIR=$OUT ninja install
'''
