[package]
name = 'mtdev'
version = '1.1.6'
description = ''
license = ''

[[source]]
source = 'https://bitmath.org/code/mtdev/mtdev-1.1.6.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
