[package]
name = 'libtirpc'
version = '1.3.4'
description = ''
license = ''

[[source]]
source = 'https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.4.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr      \
            --sysconfdir=/etc  \
            --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
