[package]
name = 'conmon'
version = '2.1.10'
description = ''
license = ''

[[source]]
source = 'https://github.com/containers/conmon/archive/refs/tags/v2.1.10.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

export PATH=$PATH:/usr/local/go/bin

make PREFIX=/usr
make DESTDIR=$OUT podman PREFIX=/usr
make DESTDIR=$OUT install PREFIX=/usr
'''
