[package]
name = 'diffutils'
version = ''
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install
'''
