[package]
name = 'iptables'
version = '1.8.10'
description = ''
license = ''

[[source]]
source = 'https://www.netfilter.org/projects/iptables/files/iptables-1.8.10.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr      \
            --disable-nftables \
            --enable-libipq

make -j$(nproc)
make DESTDIR=$OUT install
'''
