[package]
name = 'pycparser'
version = '2.21.0'
description = ''
license = ''

[[source]]
source = 'https://files.pythonhosted.org/packages/5e/0b/95d387f5f4433cb0f53ff7ad859bd2c6051051cebbb564f139a999ab46de/pycparser-2.21.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-dependencies --no-index --target=$OUT/usr/lib/python3.11/site-packages --find-links=dist pycparser
'''
