[package]
name = 'gettext'
version = '0.22'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gettext/gettext-0.22.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.22

make -j$(nproc)
make DESTDIR=$OUT install

chmod -v 0755 $OUT/usr/lib/preloadable_libintl.so
'''
