[package]
name = 'libedit'
version = '3.1'
description = ''
license = ''

[[source]]
source = 'https://www.thrysoee.dk/editline/libedit-20230828-3.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc \
            LIBS="-lncursesw"

make LIBS="-lncursesw" -j$(nproc)
make DESTDIR=$OUT install
'''
