[package]
name = 'bindgen'
version = '0.69.4'
description = ''
license = ''

[[source]]
source = 'https://github.com/rust-lang/rust-bindgen/archive/refs/tags/v0.69.4.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

$HOME/.cargo/bin/cargo build --release
mkdir -p $OUT/usr/bin
cp target/release/bindgen $OUT/usr/bin
'''
