[package]
name = 'dconf'
version = '0.40.0'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/dconf/0.40/dconf-0.40.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr           \
            --buildtype=release     \
            -Dbash_completion=false \
            ..

ninja
DESTDIR=$OUT ninja install
'''
