[package]
name = 'python3'
version = '3.11.4'
description = ''
license = ''

[[source]]
source = 'https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr        \
            --enable-shared      \
            --with-system-expat  \
            --with-system-ffi    \
            --enable-optimizations

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/etc

cat > $OUT/etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

install -v -dm755 $OUT/usr/share/doc/python-3.11.4/html
ln -sfv /usr/bin/python3.11 $OUT/usr/bin/python

#tar --strip-components=1  \
#   --no-same-owner       \
#   --no-same-permissions \
#   -C $OUT/usr/share/doc/python-3.11.4/html \
#   -xvf ../python-3.11.4-docs-html.tar.bz2
'''
