[package]
name = 'unzip'
version = '6.0'
description = ''
license = ''

[[source]]
source = 'https://downloads.sourceforge.net/infozip/unzip60.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

make -f unix/Makefile generic

make prefix=$OUT/usr MANDIR=$OUT/usr/share/man/man1 DESTDIR=$OUT \
 -f unix/Makefile install
'''
