[package]
name = 'libvdpau'
version = '1.5'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/1.5/libvdpau-1.5.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..

ninja
DESTDIR=$OUT ninja install
'''
