[package]
name = 'gdbm'
version = '1.23'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gdbm/gdbm-1.23.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat

make -j$(nproc)
make DESTDIR=$OUT install
'''
