[package]
name = 'gperf'
version = '3.1.0'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1

make -j$(nproc)
make DESTDIR=$OUT install
'''
