[package]
name = 'gpm'
version = '1.20.7'
description = ''
license = ''

[[source]]
source = 'https://anduin.linuxfromscratch.org/BLFS/gpm/gpm-1.20.7.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --sysconfdir=/etc ac_cv_path_emacs=no

make -j$(nproc)
make DESTDIR=$OUT install
'''
