[package]
name = 'limbim'
version = '1.26.4'
description = ''
license = ''

[[source]]
source = 'https://www.freedesktop.org/software/libmbim/libmbim-1.26.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
