[package]
name = 'authselect'
version = '1.5.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/authselect/authselect.git'
git_ref = '1.5.0'

[build]
script = '''
set -eux # o pipefail

autoreconf -iv

./configure --prefix=/usr --enable-silent-rules

make -j$(nproc)
make DESTDIR=$OUT install
'''
