[package]
name = 'crun'
version = '2.5.1'
description = ''
license = ''

[[source]]
source = 'https://github.com/containers/crun/releases/download/1.14.4/crun-1.14.4.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./autogen.sh

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
