[package]
name = 'gawk'
version = '5.3.0'
description = 'gawk'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gawk/gawk-5.3.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

ls
cd gawk-5.3.0

sed -i 's/extras//' Makefile.in

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install

ln -sv gawk.1 /usr/share/man/man1/awk.1

mkdir -pv                                   /usr/share/doc/gawk-5.3
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-5.3
'''
