[package]
name = 'lzo'
version = '2.10'
description = ''
license = ''

[[source]]
source = 'https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                    \
            --enable-shared                  \
            --disable-static                 \
            --docdir=/usr/share/doc/lzo-2.10

make -j$(nproc)
make DESTDIR=$OUT install
'''
