[package]
name = 'findutils'
version = '4.9.0'
description = 'findutils'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/findutils/findutils-4.9.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --localstatedir=/var/lib/locate

make -j$(nproc)
make DESTDIR=$OUT install
'''
