[package]
name = 'xbitmaps'
version = '2.5.1'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/pub/individual/data/xbitmaps-1.1.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure $XORG_CONFIG

make DESTDIR=$OUT install
'''
