[package]
name = 'libffi'
version = '3.4.4'
description = 'libffi'
license = ''

[[source]]
source = 'https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz'

[build]
script = '''
set -eux # o pipefail

ls
cd libffi-3.4.4

./configure --prefix=/usr          \
            --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
