[package]
name = 'setuptools-scm'
version = '8.0.4'
description = ''
license = ''

[[source]]
source = 'https://files.pythonhosted.org/packages/eb/b1/0248705f10f6de5eefe7ff93e399f7192257b23df4d431d2f5680bb2778f/setuptools-scm-8.0.4.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

ls -l

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --target=$OUT/usr/lib/python3.11/site-packages --find-links=dist setuptools-scm
'''
