[package]
name = 'libndp'
version = '1.8'
description = ''
license = ''

[[source]]
source = 'http://libndp.org/files/libndp-1.8.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
