[package]
name = 'glslang'
version = '14.0.0'
description = ''
license = ''

[[source]]
source = 'https://github.com/KhronosGroup/glslang/archive/refs/tags/14.0.0/glslang-14.0.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr     \
      -DCMAKE_BUILD_TYPE=Release      \
      -DALLOW_EXTERNAL_SPIRV_TOOLS=ON \
      -DBUILD_SHARED_LIBS=ON          \
      -DGLSLANG_TESTS=ON              \
      -G Ninja ..

ninja
DESTDIR=$OUT ninja install
'''
