[package]
name = 'sassc'
version = '3.6.2'
description = ''
license = ''

[[source]]
source = 'https://github.com/sass/sassc/archive/3.6.2/sassc-3.6.2.tar.gz'

[build]
script = '''
set -eux # o pipefail

wget https://github.com/sass/libsass/archive/3.6.6/libsass-3.6.6.tar.gz

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

tar -xf ../libsass-3.6.6.tar.gz
pushd libsass-3.6.6

autoreconf -fi

./configure --prefix=/usr --disable-static

make -j$(nproc)
make DESTDIR=$OUT install
'''
