[package]
name = 'gzip'
version = '1.13'
description = 'gzip'
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install
'''
