[package]
name = 'vala'
version = '0.56.14'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/vala/0.56/vala-0.56.14.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr --disable-valadoc

make -j$(nproc)
make DESTDIR=$OUT install
'''
