[package]
name = 'yasm'
version = '1.3.0'
description = ''
license = ''

[[source]]
source = 'https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i 's#) ytasm.*#)#' Makefile.in

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install
'''
