[package]
name = 'patch'
version = '2.7.6'
description = ''
license = ''

[[source]]
source = 'https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr

make -j$(nproc)
make DESTDIR=$OUT install
'''
