[package]
name = 'xorg-video-newport'
version = '0.2.4'
description = ''
license = ''

[[source]]
source = 'https://www.x.org/archive/individual/driver/xf86-video-newport-0.2.4.tar.bz2'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc

make -j$(nproc)
make DESTDIR=$OUT install
'''
