[package]
name = 'markupsafe'
version = '2.1.3'
description = ''
license = ''

[[source]]
source = 'https://pypi.org/packages/source/M/MarkupSafe/MarkupSafe-2.1.3.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir -pv $OUT/usr/lib/python3.11/site-packages

pip3 wheel -w dist --no-build-isolation --no-deps $PWD
pip3 install --no-index --find-links dist --no-cache-dir --no-user --target=$OUT/usr/lib/python3.11/site-packages Markupsafe
'''
