[package]
name = 'pulseaudio'
version = '17.0'
description = ''
license = ''

[[source]]
source = 'https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-17.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr       \
            --buildtype=release \
            -Ddatabase=gdbm     \
            -Ddoxygen=false     \
            -Dbluez5=disabled   \
            ..

ninja
DESTDIR=$OUT ninja install
'''
