[package]
name = 'libsecret'
version = '0.21.3'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libsecret/0.21/libsecret-0.21.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir bld
cd bld

meson setup --prefix=/usr       \
            --buildtype=release \
            -Dgtk_doc=false     \
            ..

ninja
DESTDIR=$OUT ninja install
'''
