[package]
name = 'attr'
version = '1.3.14'
description = ''
license = ''

[[source]]
source = 'https://github.com/silnrsi/graphite/releases/download/1.3.14/graphite2-1.3.14.tgz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=/usr ..

make -j$(nproc)
make DESTDIR=$OUT install
'''
