[package]
name = 'libnotify'
version = '0.8.3'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libnotify/0.8/libnotify-0.8.3.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr       \
            --buildtype=release \
            -Dgtk_doc=false     \
            -Dman=false         \
            ..

ninja
DESTDIR=$OUT ninja install
'''
