[package]
name = 'libgdata'
version = '0.18.1'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libgdata/0.18/libgdata-0.18.1.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr              \
            --buildtype=release        \
            -Dgtk_doc=false            \
            -Dalways_build_tests=false \
            ..

ninja
DESTDIR=$OUT ninja install
'''
