[package]
name = 'flex'
version = '2.6.4'
description = ''
license = ''

[[source]]
source = 'https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr \
            --docdir=/usr/share/doc/flex-2.6.4 \
            --disable-static

make -j$(nproc)
make DESTDIR=$OUT install

ln -sv flex   $OUT/usr/bin/lex
ln -sv flex.1 $OUT/usr/share/man/man1/lex.1
'''
