name: Package build test

on:
    push:
    schedule:
        # every day
        - cron: '0 0 * * *'
jobs:
    build_tools:
        runs-on: ubuntu-latest
        # needs to run in the most recent version of Ubuntu to ensure that the ostree version is new enough
        container: ubuntu:rolling

        steps:

        - run: apt-get update && apt-get install -y libssl-dev ostree libostree-1-1 libostree-dev git curl
        - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: actions/checkout@v2
          with:
            repository: 'ostreedev/ostree-rs-ext'
            path: 'ostree-rs-ext'

        - name: Cache
          id: cache-pkg-builder-target
          uses: actions/cache@v3
          with:
            path: util/pkg-builder/target/
            key: ${{ runner.os }}-pkg-builder-target

        - run: cargo build --release
          working-directory: util/pkg-builder
        # upload the binary as an artifact
        - uses: actions/upload-artifact@v2
          with:
            name: pkg-builder
            path: util/pkg-builder/target/release/pkg-builder

        - run: cargo build --release
          working-directory: ostree-rs-ext
        - run: ls ostree-rs-ext/target/release
        # upload the binary as an artifact
        - uses: actions/upload-artifact@v2
          with:
            name: ostree-ext-cli
            path: ostree-rs-ext/target/release/ostree-ext-cli

    build:
        runs-on: ubuntu-latest
        needs: build_tools
        # needs to run in the most recent version of Ubuntu to ensure that the ostree version is new enough
        container: ubuntu:rolling

        strategy:
            matrix:
                package: ['pkg-builder', 'bash', 'glibc', 'coreutils', 'systemd']
            # limit to 3 parallel jobs as this is currently just for testing, don't want to use up all the parallel jobs
            max-parallel: 3

        steps:
        - name: Install dependencies
          run: apt-get update && sudo apt-get install -y linux-headers-$(uname -r) meson ninja-build gperf libcap-dev autopoint ostree libostree-1-1 libostree-dev git
        - uses: actions/checkout@v2
        # download the pkg-builder binary from the previous job
        - uses: actions/download-artifact@v2
          with:
            name: pkg-builder
            path: pkg-builder
        - uses: actions/download-artifact@v2
          with:
            name: ostree-ext-cli
            path: ostree-ext-cli

        - run: chmod +x pkg-builder/pkg-builder

        - run: ../../pkg-builder/pkg-builder $PACKAGE.toml ../../out.tar.gz
          working-directory: packages/${{ matrix.package }}
          env:
              PACKAGE: ${{ matrix.package }}