[package]
name = 'gsettings-desktop-schemas'
version = '45.0'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/gsettings-desktop-schemas/45/gsettings-desktop-schemas-45.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
