[package]
name = 'wayland'
version = '1.22.0'
description = ''
license = ''

[[source]]
source = 'https://gitlab.freedesktop.org/wayland/wayland/-/releases/1.22.0/downloads/wayland-1.22.0.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      -Ddocumentation=false

ninja
DESTDIR=$OUT ninja install
'''
