[package]
name = 'libepoxy'
version = '1.5.10'
description = ''
license = ''

[[source]]
source = 'https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.10.tar.xz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

mkdir build
cd build

meson setup --prefix=/usr --buildtype=release ..

ninja
DESTDIR=$OUT ninja install
'''
