[package]
name = 'bzip2'
version = '1.0.8'
description = 'bzip2'
license = ''

[[source]]
source = 'https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

make -f Makefile-libbz2_so
make clean
make -j$(nproc)
make PREFIX=/usr DESTDIR=$OUT install

mkdir -pv $OUT/usr/{lib,bin,include}

cp -av libbz2.so.* $OUT/usr/lib
ln -sv libbz2.so.1.0.8 $OUT/usr/lib/libbz2.so

cp -v bzip2-shared $OUT/usr/bin/bzip2
for i in $OUT/usr/bin/{bzcat,bunzip2}; do
  ln -sfv bzip2 $i
done

install -v -m644 -D bzlib.h $OUT/usr/include

rm -fv $OUT/usr/lib/libbz2.a
'''
