[package]
name = 'dhcpcd'
version = '10.0.6'
description = ''
license = ''

[[source]]
source = 'https://github.com/NetworkConfiguration/dhcpcd/releases/download/v10.0.6/dhcpcd-10.0.6.tar.xz'

[[user]]
id = 52
gid = 52
name = 'dhcpcd Daemon'
login = 'dhcpcd'
home = '/var/lib/dhcpcd'
shell = '/usr/bin/false'

[[group]]
id = 52
name = 'dhcpcd'

[build]
script = '''
set -eux # o pipefail

cd $(find . -maxdepth 1 -type d | sort | head -n 2 | tail -n 1)

./configure --prefix=/usr                \
            --sysconfdir=/etc            \
            --libexecdir=/usr/lib/dhcpcd \
            --dbdir=/var/lib/dhcpcd      \
            --runstatedir=/run           \
            --privsepuser=dhcpcd

make -j$(nproc)
make DESTDIR=$OUT install

# dhcpcd home dir
install  -v -m700 -d $OUT/var/lib/dhcpcd
chown    -v 52:52 /var/lib/dhcpcd
'''
