[package]
name = 'bash'
version = '5.2'
description = 'The Bourne Again SHell'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://git.savannah.gnu.org/git/bash.git'
git_ref = 'master'

[build]
script = '''
set -eux # o pipefail

./configure --prefix=/usr                      \
            --build=$(sh support/config.guess) \
            --without-bash-malloc

make -j$(nproc)
make DESTDIR=$OUT install

mkdir -pv $OUT/usr/bin $OUT/root

ln -sv /usr/bin/bash $OUT/usr/bin/sh

cat > $OUT/root/.bashrc << "EOF"
set +h
umask 022

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/x86_64-pc-linux-gnu/bin/:/usr/lib/python3.11/site-packages/bin/:/usr/local/bin/
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig
ACLOCAL_PATH=/usr/share/aclocal
export PKG_CONFIG_PATH PATH ACLOCAL_PATH

EOF
'''
