[package]
name = 'bash'
version = '5.2'
description = 'The Bourne Again SHell'
license = 'GPL-3.0-or-later'

[[source]]
source = 'https://git.savannah.gnu.org/git/bash.git'
git_ref = 'master'

[build]
script = '''
set -eux # o pipefail

./configure --prefix=/usr                      \
            --build=$(sh support/config.guess) \
            --without-bash-malloc

make -j$(nproc)
make DESTDIR=$OUT install
ln -sv $OUT/bin/sh $OUT/usr/bin/bash
'''
